export const REGEX_PATTERNS = {
  EMAIL: /\b[\w._%+-]+@[\w.-]+\.[A-Z|a-z]{2,}\b/,
  LINKEDIN: /linkedin\.com\/in\/([\w-]+)/i,
  PHONE: /(\+\d{1,3}\s?)?(\(?\d{2,3}\)?[\s-]?)?\d{4,5}[\s-]?\d{4}/,
  PAGE_NUMBERS: /Page \d+ of \d+/gi,
  TOP_SKILLS: /Top Skills\s+([\s\S]+?)(?:Languages)/i,
  LANGUAGES: /Languages\s+([\s\S]+?)(?:Summary|Experience|Education|$)/i,
  SUMMARY: /Summary\s+([\s\S]+?)(?:Experience|Education|$)/i,
  EXPERIENCE: /Experience\s+([\s\S]+?)(?:Education|$)/i,
  EDUCATION: /Education\s+([\s\S]+?)(?:$)/i,
  NAME: /^([A-Z][a-z]+(?: [A-Z][a-z]+)*)/m,
  LOCATION: /([A-Z][a-z]+(?:,\s*[A-Z][a-z]+)*(?:,\s*[A-Z]{2,})?)/,
  LANGUAGE_PROFICIENCY: /(Native|Professional|Elementary|Limited)/i,
  DATE_RANGE: /(\w+\s+\d{4})\s*[-–]\s*(\w+\s+\d{4}|Present)/i,
  YEAR: /\b(19|20)\d{2}\b/g,
  LINE_BREAK: /\r?\n/g,
  MULTIPLE_SPACES: /\s{2,}/g,
  BULLET_POINTS: /^[\u2022•]\s*/gm,
} as const;

